#!/usr/bin/python3

import datetime
import time

import goeapi
from energymon.energymon import EnergyMon


# XXX make configurable
GO_E = "192.168.178.109"

DEFAULT_SLEEP = 60

class EloaderController:
    def __init__(self):
        self.mon = EnergyMon()
        self.goe = goeapi.GoeAPI(GO_E)
        self.last_connect = 0.0
        self.current_phases = self.goe.phases
        self.current_ampere = self.goe.ampere

    def loop(self):
        while True:
            try:
                sleeptime = self.tick()
            except OSError as e:
                print(f"network error {e}")
                sleeptime = DEFAULT_SLEEP
            # wait a bit
            time.sleep(sleeptime)

    def log(self, *args):
        print(*args, flush=True)

    def now(self):
        return datetime.datetime.now()

    def manual_overriden(self):
        return self.current_phases != 1

    def tick(self):
        if self.manual_overriden():
            self.log(
                "ampere or phases got manually overriden got {}/{} sleeping "
                "until it goes back to 1 phase ".format(
                    self.goe.ampere,
                    self.goe.phases,
                )
            )
            return DEFAULT_SLEEP

        current_power_charger = self.goe.power / 1000.0
        available_power = -self.mon.current.current_power / 1000.0
        self.last_connect = time.time()
        self.log(
            "available {} kW / charger {} kW".format(
                available_power, current_power_charger
            )
        )
        next_amp = None
        for amp in [6, 10, 12, 14, 16]:
            pw = 220 * amp * self.current_phases / 1000.0
            if pw > available_power:
                break
            next_amp = amp
        if self.current_ampere != next_amp:
            if next_amp is None:
                self.log("not enough power, forcing pause")
                self.goe.force_pause = True
            if next_amp is not None:
                if self.goe.force_pause:
                    self.log("enough power, un-pause")
                    self.goe.force_pause = False
                self.goe.ampere = next_amp
                new_kw = 220 * next_amp * self.current_phases / 1000.0
                self.log("switched to {} amp ({} kW)".format(next_amp, new_kw))
            self.current_ampere = next_amp
        else:
            self.log("staying at {} amp".format(self.current_ampere))
        return DEFAULT_SLEEP


def main():
    el = EloaderController()
    el.loop()


if __name__ == "__main__":
    main()
