#!/usr/bin/python3

import datetime
import sys
import time

import goeapi
from energymon.energymon import EnergyMon


# XXX make configurable
GO_E = "192.168.178.109"

DEFAULT_SLEEP = 5 * 60
ERROR_SLEEP = 60


class EloaderController:
    def __init__(self):
        self.mon = EnergyMon()
        self.goe = goeapi.GoeAPI(GO_E)
        self.last_connect = 0.0
        self.current_phases = self.goe.phases
        self.current_ampere = self.goe.ampere

    def loop(self):
        while True:
            try:
                sleeptime = self.tick()
            except OSError as e:
                print(f"network error {e}")
                sleeptime = DEFAULT_SLEEP
            # wait a bit
            time.sleep(sleeptime)

    def log(self, *args):
        print(*args, flush=True)

    def now(self):
        return datetime.datetime.now()

    def manual_overriden(self):
        return self.current_phases != 1

    def tick(self):
        if self.manual_overriden():
            self.log(
                f"ampere or phases got manually overriden got {self.goe.ampere}/{self.goe.phases} "
                "sleeping until it goes back to 1 phase "
            )
            return DEFAULT_SLEEP

        current_power_charger = self.goe.power / 1000.0
        # XXX: move to threading? directly in EnergyMon()?
        try:
            self.mon._read()
        except Exception as e:
            self.log(f"error reading from enery mon: {e}")
            return ERROR_SLEEP
        available_power = -self.mon.current.current_power / 1000.0
        self.last_connect = time.time()
        self.log(
            f"available: {available_power} kW, charger: {current_power_charger} kW"
        )
        if available_power < (220 * 6 / 1000.0):
            self.log("not enough power, forcing pause")
            self.goe.force_pause = True
            return DEFAULT_SLEEP
        for amp in [16, 14, 12, 10, 6]:
            pw = 220 * amp / 1000.0
            if pw < available_power:
                needs_switching = self.current_ampere != amp
                if needs_switching:
                    self.goe.ampere = amp
                    self.current_ampere = amp
                if self.goe.force_pause:
                    self.log("enough power, un-pause")
                    self.goe.force_pause = False
                self.log(f"switched: {needs_switching}, amp: {amp}, kW: {pw}")
                return DEFAULT_SLEEP
        self.log(f"internal error: should never be reached {available_power!r}")
        return DEFAULT_SLEEP


def main():
    if len(sys.argv) > 1:
        global DEFAULT_SLEEP
        DEFAULT_SLEEP = int(sys.argv[1])
    el = EloaderController()
    el.loop()


if __name__ == "__main__":
    main()
